apiVersion: v1
kind: Service
metadata:
  name: monolitic-app-service
  labels:
    app: monolitic-app
spec:
  selector:
   app: monolitic-app
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000  # Puerto en el que Flask está escuchando dentro del contenedor
    #nodePort: 30100